# Generated by Django 3.2.12 on 2023-09-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('collector_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=50)),
                ('inward_number', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('Request_Date_Time', models.DateTimeField()),
                ('Status', models.CharField(max_length=50)),
                ('talati_id', models.IntegerField()),
                ('Issue_Date_Time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Talati',
            fields=[
                ('talati_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('mobile_number', models.BigIntegerField()),
                ('address', models.TextField()),
                ('verification_code', models.IntegerField()),
                ('signature', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('mobile_number', models.BigIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('village_id', models.IntegerField()),
                ('verification_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('VillageId', models.AutoField(primary_key=True, serialize=False)),
                ('village_name', models.CharField(max_length=50)),
                ('talati_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('options_list_json', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('result_json', models.TextField()),
                ('result_date_time', models.DateTimeField()),
                ('voted_user_list', models.TextField()),
                ('village_id', models.IntegerField()),
            ],
        ),
    ]
