# Generated by Django 3.2.12 on 2023-09-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_auto_20230909_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('answer', models.TextField(blank=True)),
                ('complaint_date_time', models.DateTimeField()),
                ('resolve_date_time', models.DateTimeField(blank=True)),
                ('sender_username', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='village_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
