# Generated by Django 3.2.12 on 2023-09-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_auto_20230910_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='resolve_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
