# Generated by Django 3.2.12 on 2023-09-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_alter_complaints_resolve_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('tax_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('ward_no', models.CharField(max_length=50)),
                ('tenament_no', models.TextField()),
                ('amount', models.IntegerField()),
                ('payer_username', models.CharField(max_length=50)),
                ('occupier_name', models.CharField(max_length=50)),
                ('occupier_address', models.CharField(max_length=50)),
                ('payment_date_time', models.DateTimeField()),
            ],
        ),
    ]
