# Generated by Django 3.2.12 on 2023-09-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_auto_20230910_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
