# Generated by Django 3.2.12 on 2023-09-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_tax_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
