# Generated by Django 3.2.12 on 2023-09-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0012_tax_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='payment_method',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
