# Generated by Django 3.2.12 on 2023-09-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0013_tax_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='village_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
