# Generated by Django 3.2.12 on 2023-09-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0014_alter_profile_village_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthCertificate',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('inward_id', models.CharField(blank=True, max_length=50, null=True)),
                ('fullname', models.TextField()),
                ('father_name', models.TextField()),
                ('mother_name', models.TextField()),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=50)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.TextField()),
                ('weight', models.IntegerField()),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('form_status', models.CharField(max_length=50)),
                ('application_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
