# Generated by Django 3.2.12 on 2023-09-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0015_birthcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthcertificate',
            name='document_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
