# Generated by Django 3.2.12 on 2023-09-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0016_birthcertificate_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthcertificate',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
