# Generated by Django 3.2.12 on 2023-09-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0017_alter_birthcertificate_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthcertificate',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/birthcertificate/'),
        ),
    ]
