# Generated by Django 3.2.12 on 2023-09-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0018_alter_birthcertificate_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthcertificate',
            name='document_name',
        ),
        migrations.AddField(
            model_name='birthcertificate',
            name='talati_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='birthcertificate',
            name='user_villageId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
