# Generated by Django 3.2.12 on 2023-09-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0020_auto_20230919_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthcertificate',
            name='weight',
            field=models.FloatField(),
        ),
    ]
