# Generated by Django 3.2.12 on 2023-09-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0023_incomecertificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomecertificate',
            name='id_proof',
        ),
    ]
