# Generated by Django 3.2.12 on 2023-09-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0024_remove_incomecertificate_id_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandOwnershipCertificate',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('inward_id', models.CharField(blank=True, max_length=50, null=True)),
                ('fullname', models.TextField()),
                ('gender', models.CharField(max_length=50)),
                ('district', models.TextField()),
                ('taluka', models.TextField()),
                ('village', models.TextField()),
                ('voter_id_no', models.CharField(blank=True, max_length=50, null=True)),
                ('land_description', models.TextField()),
                ('land_use', models.TextField()),
                ('photo', models.FileField(blank=True, null=True, upload_to='uploads/landcertificate/')),
                ('st_certificate', models.FileField(blank=True, null=True, upload_to='uploads/landcertificate/')),
                ('land_posession_certi', models.FileField(blank=True, null=True, upload_to='uploads/landcertificate/')),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('form_status', models.CharField(max_length=50)),
                ('application_date', models.DateTimeField(blank=True, null=True)),
                ('talati_id', models.IntegerField(blank=True, null=True)),
                ('user_villageId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NonCreamyLayerCertificate',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('inward_id', models.CharField(blank=True, max_length=50, null=True)),
                ('fullname', models.TextField()),
                ('gender', models.CharField(max_length=50)),
                ('parent_name', models.TextField()),
                ('religion', models.TextField()),
                ('cast', models.TextField()),
                ('subcast', models.TextField()),
                ('district', models.TextField()),
                ('taluka', models.TextField()),
                ('village', models.TextField()),
                ('photo', models.FileField(blank=True, null=True, upload_to='uploads/nclcertificate/')),
                ('leaving_certificate', models.FileField(blank=True, null=True, upload_to='uploads/nclcertificate/')),
                ('income_certificate', models.FileField(blank=True, null=True, upload_to='uploads/nclcertificate/')),
                ('cast_certificate', models.FileField(blank=True, null=True, upload_to='uploads/nclcertificate/')),
                ('ration_card', models.FileField(blank=True, null=True, upload_to='uploads/nclcertificate/')),
                ('electricity_bill', models.FileField(blank=True, null=True, upload_to='uploads/nclcertificate/')),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('form_status', models.CharField(max_length=50)),
                ('application_date', models.DateTimeField(blank=True, null=True)),
                ('talati_id', models.IntegerField(blank=True, null=True)),
                ('user_villageId', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='castcertificate',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/castcertificate/'),
        ),
    ]
