# Generated by Django 3.2.12 on 2023-10-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0025_auto_20230928_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allocated_villages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
