# Generated by Django 3.2.12 on 2023-10-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0026_profile_allocated_villages'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('news_date_time', models.DateTimeField()),
                ('sender_id', models.IntegerField()),
            ],
        ),
    ]
