# Generated by Django 3.2.12 on 2023-10-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0027_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='talati_id',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
    ]
