# Generated by Django 3.2.12 on 2023-10-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0030_alter_profile_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='modules/static/uploads/signatures/'),
        ),
    ]
