# Generated by Django 3.2.12 on 2023-10-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0031_alter_profile_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomecertificate',
            name='rupee_in_words',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
