# Generated by Django 3.2.12 on 2023-10-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0033_auto_20231018_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='deathcertificate',
            name='district',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deathcertificate',
            name='taluka',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deathcertificate',
            name='village',
            field=models.TextField(blank=True, null=True),
        ),
    ]
