# Generated by Django 3.2.12 on 2023-10-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0034_auto_20231018_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='landownershipcertificate',
            name='acres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landownershipcertificate',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landownershipcertificate',
            name='parent_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
